### ISSUE TITLE
invalid xsi type

### ISSUE THREAD

**Issue by mpbill** [eth0izzle/NLog.Slack#10]
I had this working previously, but now when I add the slack target to my Nlog.config:

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true">

  <extensions>
    <add assembly="NlogViewer" />
    <add assembly="NLog.Slack" />
  </extensions>
  <targets async="true">
    <target name="logfile" xsi:type="File" fileName="ABFS_EmailGenerator.log"/>

    <target xsi:type="NLogViewer" name="ctrl" />
    <target xsi:type="Slack"
            name="slackTarget"
            layout="${message}"
            webHookUrl="https://xxx.slack.com/services/hooks/incoming-webhook?token=xxx"
            channel="#log"
            username="NLog.Slack"
            compact="false"
            icon=":ghost:" />
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="logfile,ctrl" />
    <logger name="*" minlevel="Warn" writeTo="logfile,ctrl,slackTarget"/>
    <logger name="Slacker" minlevel="Info" writeTo="slackTarget"/>

  </rules>
</nlog>
```

the slack target has an error which is `This is an invalid xsi:type 'http://www.nlog-project.org/schemas/NLog.xsd:Slack`.  and none of the logs get sent to the slack channel.  I have re-generated the webhook token url, cant figure out what is going wrong.

**Comment by kdx-perbol** [comment]
The _invalid XSI type_ error is because NLog.Slack does not update the NLog XSD schema, so the configuration schema does not recognize `Slack` as an Nog target type. This does not affect actual NLog functionality, it only affects configuration file validation.

If you have `throwExceptions="true"` as in your example, and nothing is sent to Slack, then something else is wrong.

**Comment by kdx-perbol** [comment]
NLog.Slack should add to the NLog XSD to prevent this. I've added the necessary bits myself to my own NLog XSD avoid any confusion.

**Comment by eth0izzle** [comment]
@kdx-perbol can you submit a PR please?

**Comment by kdx-perbol** [comment]
It seems I couldn't.
