### ISSUE TITLE
Nuget package has wrong dependencies

### ISSUE THREAD

**Issue by cwesterlund** [eth0izzle/NLog.Slack#11]
Hi,
I have had som issues with Nlog.Slack.
I found out that a dependency is now NewtonSoft.Json but it isn't stated in the Nlog.Slack nuget package.
Instead a dependency is ServiceStack.Text which I thought you removed according to this issue:
https://github.com/eth0izzle/NLog.Slack/pull/4

Also, when I download the source the version on Nlog.Slack is 1.0.1, not 1.0.2. Isn't the latest code in git?

Regards,
Christian

**Comment by gurufordy** [comment]
I just had the same issues as Christian. Luckily I found this as I couldn't understand why one project wasn't working whereas the other did. Turned out to be the NewtonSoft.Json package being missing!

Is this project dead or still going?

**Comment by cyrilgandon** [comment]
@gurufordy : @eth0izzle doesn't seems to be active on GitHub anymore. I have made PR for removing those dependencies, you can check them out. I have also fork the project to keep updated with last version of NLog : https://github.com/cyrilgandon/NLogToSlack

**Comment by gurufordy** [comment]
Nice one Cyril, got the feeling this was not as alive as I'd like so I've made the switch to your forked project :+1:

**Comment by eth0izzle** [comment]
Thanks for the PR Cyril, I'll merge in today!

**Comment by cyrilgandon** [comment]
Hi @eth0izzle glad to see you again, NLog.Slack has been a great help for my projects. Nlog 4.3 will be out pretty soon, do you plan to update the dependency? 
https://github.com/NLog/NLog/releases
I've made a PR for updating to 4.0.1 a while ago, I can update it if necessary!

**Comment by eth0izzle** [comment]
Yes, I'm going to do an update this weekend :)

**Comment by snakefoot** [comment]
Created #15 that resolves this issue.
