### ISSUE TITLE
Missing correct AsyncLogEventInfo callback

### ISSUE THREAD

**Issue by snakefoot** [eth0izzle/NLog.Slack#13]
When overriding:

`protected override void Write(AsyncLogEventInfo info)`

Then you should also need to notify when the AsyncLogEventInfo completes with success.

I would probably remove the try-catch and Error-event from SlackClient, and add this **bold line**:

protected override void Write(AsyncLogEventInfo info)
{
  try
  {
    this.SendToSlack(info);
    **info.Continuation(null);**
  }
  catch (Exception e)
  {
    info.Continuation(e);
  }
}

**Comment by eth0izzle** [comment]
Good shout - can you submit a PR please

**Comment by kdx-perbol** [comment]
How's that PR coming @snakefoot?

**Comment by snakefoot** [comment]
@eth0izzle Created #15 for you
