### ISSUE TITLE
problem with Nlog config

### ISSUE THREAD

**Issue by fox-infonote** [eth0izzle/NLog.Slack#18]
Hi,

trying to use this in a project running .Net 4.7. Nlog at 4.5.11 and Nlog.Slack at 1.04

config looks like this 
`<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true">
    <extensions>
      
      <add assembly="NLog.Slack" />
    </extensions>
    <targets>
      <target name="InfoLog" xsi:type="File" layout="${longdate} ${logger} ${message} " fileName="${basedir}\logs\Mylogs.log" archiveFileName="${basedir}\logs\Information.{#}.log" archiveEvery="Day" archiveNumbering="Rolling" maxArchiveFiles="3" concurrentWrites="true" keepFileOpen="false" encoding="iso-8859-2" />
          <target xsi:type="Slack"		name="slack_Debug" 		layout="${longdate}|${level:uppercase=true}  ${logger} ${message}  ${exception:format=tostring} "
		webHookUrl="https://hooks.slack.com/services/XXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX"
		channel="#test" 		username="Calcite_Web" 		compact="false" 		icon=":ghost:" />
</targets>
 <rules>
      <logger name="mylog" levels="Info,Warn,Error" writeTo="InfoLog" />
</rules>
<nlog>`

when I call  NLog.LogManager.GetLogger(loggername)
I get an error 

An error occurred creating the configuration section handler for nlog: Exception when parsing web.config. 

looking at the inner exception i can see Parameter channel not supported on SlackTarget
any ideas ?

**Comment by snakefoot** [comment]
Some strange commit was made by @eth0izzle just before making the release, where a lot of code was ripped out and replaced., Not sure why. It looks like a dependency update going very wrong.

**Comment by fox-infonote** [comment]
wonder whats happened to @eth0izzle usually his commit messages are so specific. Lots of lovely updates doesn't say much especially when it appears to remove loads of features.

**Comment by fox-infonote** [comment]
I understand the issue is with this update. Wish I knew why it was done. Will close this as I suspect this is now a feature.

**Comment by eth0izzle** [comment]
It’s because Slack no longer support passing in the channel, icon or name parameters. You have to define them in your Slack App now. I need to update the XSD to remove the params

**Comment by fox-infonote** [comment]
Thanks for that. Oh what a nightmare this is going to cause !

Still I can understand that lots of people are avoiding the free 10 app limit by setting these.

Thanks for the feedback


Regards

John Woodford
Senior developer
t: 01858 467746 m: 07967 486099
Bespoke Software | Workflow Solutions | Smartphone Apps
www.Infonote.com<http://www.infonote.com/>

**Comment by eth0izzle** [comment]
Oh I know your pain. If I’m being honest I could of handled it better. Perhaps thrown a warning instead of cutting it out- didn’t realise it would throw an exception!
