### ISSUE TITLE
Suggested mods

### ISSUE THREAD

**Issue by georgiosd** [eth0izzle/NLog.Slack#5]
Hi! 

I have the following suggestions for the project - if you think they're good, I can submit a pull request:
- Use JSON.NET instead of ServiceStack because it's used more widely and there's a high chance it will already be there. 
- Add a parameter which will allow you to specify which fields are displayed in table format below the message.

Thanks

**Comment by cyrilgandon** [comment]
Hi,

For ServiceStack dependency, I think this pull handle it : https://github.com/eth0izzle/NLog.Slack/pull/4

**Comment by eth0izzle** [comment]
I merged in the JSON.NET pull request for now. As @cyrilgandon pointed out I think it's probably best to do this natively, rather than relying on a third party lib. I'll update ASAP.

**Comment by georgiosd** [comment]
It's easy enough to switch! 

How do you feel about the second suggestion?
